
// This file is automatically generated. Do not modify.
import { type FirebaseOptions } from 'firebase/app';

export const firebaseConfig: FirebaseOptions = {
  apiKey: "AIzaSyByp5VeFvNpLgpBLie8lwBRm0sNyiCph3I",
  authDomain: "studio-2296895549-5fe2c.firebaseapp.com",
  projectId: "studio-2296895549-5fe2c",
  storageBucket: "studio-2296895549-5fe2c.appspot.com",
  messagingSenderId: "842772495994",
  appId: "1:842772495994:web:e962d2aa56c54ae3ee05c3",
};
